/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface ButtonP {
    'day': string;
    'month': string;
    'year': string;
  }
  interface ButtonPAttributes extends StencilHTMLAttributes {
    'day'?: string;
    'month'?: string;
    'year'?: string;
  }

  interface MyComponent {
    'day': string;
    'month': string;
    'year': string;
  }
  interface MyComponentAttributes extends StencilHTMLAttributes {
    'day'?: string;
    'month'?: string;
    'year'?: string;
  }

  interface PanelP {
    'day': string;
    'month': string;
    'year': string;
  }
  interface PanelPAttributes extends StencilHTMLAttributes {
    'day'?: string;
    'month'?: string;
    'onCompleted'?: (event: CustomEvent) => void;
    'year'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'ButtonP': Components.ButtonP;
    'MyComponent': Components.MyComponent;
    'PanelP': Components.PanelP;
  }

  interface StencilIntrinsicElements {
    'button-p': Components.ButtonPAttributes;
    'my-component': Components.MyComponentAttributes;
    'panel-p': Components.PanelPAttributes;
  }


  interface HTMLButtonPElement extends Components.ButtonP, HTMLStencilElement {}
  var HTMLButtonPElement: {
    prototype: HTMLButtonPElement;
    new (): HTMLButtonPElement;
  };

  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLPanelPElement extends Components.PanelP, HTMLStencilElement {}
  var HTMLPanelPElement: {
    prototype: HTMLPanelPElement;
    new (): HTMLPanelPElement;
  };

  interface HTMLElementTagNameMap {
    'button-p': HTMLButtonPElement
    'my-component': HTMLMyComponentElement
    'panel-p': HTMLPanelPElement
  }

  interface ElementTagNameMap {
    'button-p': HTMLButtonPElement;
    'my-component': HTMLMyComponentElement;
    'panel-p': HTMLPanelPElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
